# Generated by Django 6.0.4 on 2026-05-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reciver',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
