# Generated by Django 6.0.4 on 2026-05-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_userbookrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='status',
            field=models.CharField(choices=[('wish', 'Wishlist'), ('read', 'Read'), ('current', 'current'), ('borrowed', 'Borrowed'), ('favourite', 'favourite')], default='wish', max_length=20),
        ),
    ]
